#test re-assignment of value in inner scope
result {
	value:int
	| mutable error {
		message:string
	}
}

t:result = @result.error with { message = "No go" }

match(t)
	value {
		print("Value: " + value)
	}
	| error {
		error = @result.error with { message = "Reassigned!" }
		print("Error: " + error.message)
	}
