#test re-assignment of value in outer scope
result {
	value:int
	| error {
		message:string
	}
}

t:result= @result.error with { message = "No go" }

t2:result

match(t)
	value {
		print("Value: " + value)
	}
	| error {
		t2 = error
		print("Error: " + error.message)
	}
