#test re-assignment of value in inner scope
result {
	value:int
	| error {
		message:string
	}
}

t:result= @result.error with { message = "No go" }

match(t)
	error {
		error = @result.error with { message = "Reassigned!" }
		print("Error: " + error.message)
	}
